import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-view-all-student',
  templateUrl: './view-all-student.component.html',
  styleUrls: ['./view-all-student.component.css']
})
export class ViewAllStudentComponent implements OnInit {

  constructor() { }
  studentData=[
  {
    "name":"Abhinand",
    "rollNo":"4",
    "admissionNo":"7337",
    "college":"GECI",
    "department":"IT",
    "bloodGroup":"A+",
    "dob":"05/04/2000",
    "parentName":"Manoharan",
    "parentEmailId":"manoharan@gmail.com",
    "guardianName":"Manoharan",
    "guardianAddress":"Kozhikode"
  },
  {
    "name":"Riya",
    "rollNo":"22",
    "admissionNo":"7222",
    "college":"GECK",
    "department":"CS",
    "bloodGroup":"B+",
    "dob":"04/07/2001",
    "parentName":"Rajeev",
    "parentEmailId":"rajeev@gmail.com",
    "guardianName":"Rajeev",
    "guardianAddress":"Kannur"
  },
  {
    "name":"Anuruth",
    "rollNo":"15",
    "admissionNo":"7415",
    "college":"GECW",
    "department":"ME",
    "bloodGroup":"O+",
    "dob":"05/07/2000",
    "parentName":"Soman",
    "parentEmailId":"soman@gmail.com",
    "guardianName":"Soman",
    "guardianAddress":"Kottayam"
  },
  {
    "name":"Hafis",
    "rollNo":"11",
    "admissionNo":"7811",
    "college":"GECI",
    "department":"EEE",
    "bloodGroup":"A+",
    "dob":"08/05/2000",
    "parentName":"Jafoor",
    "parentEmailId":"jafoor@gmail.com",
    "guardianName":"Jafoor",
    "guardianAddress":"Malappuram"
  },
  {
    "name":"Basith",
    "rollNo":"34",
    "admissionNo":"7234",
    "college":"NSS",
    "department":"EC",
    "bloodGroup":"A-",
    "dob":"09/11/2000",
    "parentName":"Ameen",
    "parentEmailId":"ameen@gmail.com",
    "guardianName":"Ameen",
    "guardianAddress":"Malapppuram"
  },
  {
    "name":"Havin",
    "rollNo":"21",
    "admissionNo":"7221",
    "college":"GECI",
    "department":"IT",
    "bloodGroup":"B-",
    "dob":"05/02/2000",
    "parentName":"Biju",
    "parentEmailId":"biju@gmail.com",
    "guardianName":"Biju",
    "guardianAddress":"Palakkad"
  },
  {
    "name":"Surya",
    "rollNo":"44",
    "admissionNo":"7844",
    "college":"GECK",
    "department":"EEE",
    "bloodGroup":"A+",
    "dob":"06/01/2000",
    "parentName":"Chandran",
    "parentEmailId":"chandran@gmail.com",
    "guardianName":"Chandran",
    "guardianAddress":"Palakkad"
  },
  {
    "name":"Akshay",
    "rollNo":"12",
    "admissionNo":"7112",
    "college":"GECT",
    "department":"ME",
    "bloodGroup":"A-",
    "dob":"27/02/2000",
    "parentName":"Pavithran",
    "parentEmailId":"pavithran@gmail.com",
    "guardianName":"Pavithran",
    "guardianAddress":"Kozhikode"
  },
  {
    "name":"Kripa",
    "rollNo":"28",
    "admissionNo":"7828",
    "college":"GECM",
    "department":"IT",
    "bloodGroup":"B-",
    "dob":"06/03/2000",
    "parentName":"Pathmakumar",
    "parentEmailId":"pathmakumar@gmail.com",
    "guardianName":"Pathmakumar",
    "guardianAddress":"Kollam"
  },
  {
    "name":"Silpa",
    "rollNo":"44",
    "admissionNo":"7944",
    "college":"GECT",
    "department":"CS",
    "bloodGroup":"O+",
    "dob":"07.01/2000",
    "parentName":"Ramesh",
    "parentEmailId":"ramesh@gmail.com",
    "guardianName":"Ramesh",
    "guardianAddress":"Kozhikode"
  }
]
  ngOnInit(): void {
  }

}
